#!/usr/bin/env python3
"""Generate app/src/main/java/com/xnotes/ui/icons/Ph.kt from Phosphor Core SVGs.

Phosphor (MIT): https://github.com/phosphor-icons/core. Fetch the assets once into a scratch folder:
    npm pack @phosphor-icons/core@2.1.1 && tar -xzf phosphor-icons-core-2.1.1.tgz
then, from the repo root:
    python tools/phosphor/gen_phosphor.py <scratch>/package/assets
Icons and weights come from tools/phosphor/icons.txt ("name weight[,weight]" per line, # comments).
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'tools' / 'phosphor' / 'icons.txt'
OUT = ROOT / 'app' / 'src' / 'main' / 'java' / 'com' / 'xnotes' / 'ui' / 'icons' / 'Ph.kt'
WEIGHTS = ('regular', 'fill', 'duotone')
KEYWORDS = {'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if', 'in',
            'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this', 'throw',
            'true', 'try', 'typealias', 'typeof', 'val', 'var', 'when', 'while'}
TAG = re.compile(r'<([a-zA-Z][\w-]*)')
PATH = re.compile(r'<path\b([^>]*?)/?>')
ATTR = re.compile(r'([\w-]+)="([^"]*)"')


def kotlin_name(name, weight):
    parts = name.split('-')
    ident = parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])
    if weight != 'regular':
        ident += weight.capitalize()
    return f'`{ident}`' if ident in KEYWORDS else ident


def layers(svg, where):
    for tag in TAG.findall(svg):
        if tag not in ('svg', 'path'):
            sys.exit(f'{where}: <{tag}> is not supported; only <path> elements are converted')
    out = []
    for m in PATH.finditer(svg):
        attrs = dict(ATTR.findall(m.group(1)))
        if 'd' not in attrs:
            sys.exit(f'{where}: a <path> has no d attribute')
        out.append((attrs['d'], float(attrs.get('opacity', '1'))))
    if not out:
        sys.exit(f'{where}: no <path> found')
    return out


def read_manifest():
    entries = set()
    for n, raw in enumerate(MANIFEST.read_text(encoding='utf-8').splitlines(), 1):
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        name, _, weights = line.partition(' ')
        for w in (x.strip() for x in weights.split(',')):
            if w not in WEIGHTS:
                sys.exit(f'icons.txt:{n}: unknown weight "{w}"')
            entries.add((name, w))
    return sorted(entries)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    assets = pathlib.Path(sys.argv[1])
    body = []
    for name, weight in read_manifest():
        svg = assets / weight / (f'{name}.svg' if weight == 'regular' else f'{name}-{weight}.svg')
        if not svg.exists():
            sys.exit(f'missing {svg}')
        parts = [f'PhLayer("{d}")' if a == 1 else f'PhLayer("{d}", {a:g}f)'
                 for d, a in layers(svg.read_text(encoding='utf-8'), svg.name)]
        label = name if weight == 'regular' else f'{name}-{weight}'
        body.append(f'    val {kotlin_name(name, weight)}: ImageVector by lazy {{ phosphor("{label}", {", ".join(parts)}) }}')
    head = [
        '// GENERATED by tools/phosphor/gen_phosphor.py from @phosphor-icons/core 2.1.1 (MIT, see',
        '// assets/licenses/phosphor.txt). Do not edit: add the icon to tools/phosphor/icons.txt and rerun.',
        'package com.xnotes.ui.icons',
        '',
        'import androidx.compose.ui.graphics.vector.ImageVector',
        '',
        '/** Phosphor icons, Regular unless the name ends in Fill or Duotone. Each is built on first use. */',
        'object Ph {',
    ]
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(head + body + ['}']) + '\n')
    print(f'wrote {OUT.relative_to(ROOT)}: {len(body)} icons')


if __name__ == '__main__':
    main()
