#!/usr/bin/env python3
"""Generate app/src/main/java/com/xnotes/ui/icons/Fl.kt from Microsoft Fluent System Icons SVGs.

Fluent System Icons (MIT, see tools/fluent/LICENSE): https://github.com/microsoft/fluentui-system-icons.
The SVGs are the Regular 24 px files of @fluentui/svg-icons 1.1.265 (icons/<name>_24_regular.svg), kept in a
scratch folder. From the repo root:
    python tools/fluent/gen_fluent.py <scratch folder holding the *_24_regular.svg files>
Icons come from tools/fluent/icons.txt (one name per line, the file stem without _24_regular; # comments).
Each SVG is a 24 x 24 viewBox of filled <path>s; a fill-rule="evenodd" path keeps its rule.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'tools' / 'fluent' / 'icons.txt'
OUT = ROOT / 'app' / 'src' / 'main' / 'java' / 'com' / 'xnotes' / 'ui' / 'icons' / 'Fl.kt'
KEYWORDS = {'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if', 'in',
            'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this', 'throw',
            'true', 'try', 'typealias', 'typeof', 'val', 'var', 'when', 'while'}
TAG = re.compile(r'<([a-zA-Z][\w-]*)')
PATH = re.compile(r'<path\b([^>]*?)/?>')
SVG = re.compile(r'<svg\b([^>]*)>')
ATTR = re.compile(r'([\w-]+)="([^"]*)"')


def kotlin_name(name):
    parts = name.split('_')
    ident = parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])
    return f'`{ident}`' if ident in KEYWORDS else ident


def paths(svg, where):
    for tag in TAG.findall(svg):
        if tag not in ('svg', 'path'):
            sys.exit(f'{where}: <{tag}> is not supported; only <path> elements are converted')
    head = SVG.search(svg)
    view = dict(ATTR.findall(head.group(1))).get('viewBox') if head else None
    if view != '0 0 24 24':
        sys.exit(f'{where}: viewBox is {view!r}, not "0 0 24 24"')
    out = []
    for m in PATH.finditer(svg):
        attrs = dict(ATTR.findall(m.group(1)))
        if 'd' not in attrs:
            sys.exit(f'{where}: a <path> has no d attribute')
        rule = attrs.get('fill-rule', 'nonzero')
        if rule not in ('nonzero', 'evenodd'):
            sys.exit(f'{where}: unknown fill-rule "{rule}"')
        out.append((attrs['d'], rule == 'evenodd'))
    if not out:
        sys.exit(f'{where}: no <path> found')
    return out


def read_manifest():
    names = set()
    for raw in MANIFEST.read_text(encoding='utf-8').splitlines():
        line = raw.split('#', 1)[0].strip()
        if line:
            names.add(line)
    return sorted(names)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    folder = pathlib.Path(sys.argv[1])
    body = []
    for name in read_manifest():
        svg = folder / f'{name}_24_regular.svg'
        if not svg.exists():
            sys.exit(f'missing {svg}')
        parts = [f'FlPath("{d}", evenOdd = true)' if odd else f'FlPath("{d}")'
                 for d, odd in paths(svg.read_text(encoding='utf-8'), svg.name)]
        body.append(f'    val {kotlin_name(name)}: ImageVector by lazy {{ fluent("{name}", {", ".join(parts)}) }}')
    head = [
        '// GENERATED by tools/fluent/gen_fluent.py from @fluentui/svg-icons 1.1.265, Regular 24 (MIT, see',
        '// assets/licenses/fluent-system-icons.txt). Do not edit: add the icon to tools/fluent/icons.txt and rerun.',
        'package com.xnotes.ui.icons',
        '',
        'import androidx.compose.ui.graphics.vector.ImageVector',
        '',
        '/** Microsoft Fluent System Icons, Regular: the selection bar, its More menu and its settings. Each is built on first use. */',
        'object Fl {',
    ]
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(head + body + ['}']) + '\n')
    print(f'wrote {OUT.relative_to(ROOT)}: {len(body)} icons')


if __name__ == '__main__':
    main()
